// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pftjdlibidiopqlzracd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmdGpkbGliaWRpb3BxbHpyYWNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDM1NzQsImV4cCI6MjA2NTY3OTU3NH0.h9x4rKSE4zPe5RvD8UQMkT2BvZeFSAPrN_wquHRCW64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);